### ISSUE TITLE
Urwid client is broken

### ISSUE THREAD

**Issue by MineRobber9000** [desvox/bbj#6]
main.py, line 1894: SyntaxError: only named arguments may follow *expression

I'll post more errors as I find them.

**Comment by desvox** [comment]
That is valid syntax for me on python 3.5. I will set up some other python versions and do better testing this afternoon. But try running on python3.5 and see if all these errors go away. Because the server and client are both peachy for me with 3.5.

If its broken on 3.4, i _will_ make adjustments to make it run there. But i will not support anything older than that.

**Comment by MineRobber9000** [comment]
This causes MANY problems. The server runs fine under 3.4 but the client doesn't? Also, the server I'm using is running Debian, which, to the best of my knowledge, doesn't have Python 3.5<sup>[citation needed]</sup>. As such, I'm left out of using BBJ for the community I'm a part of. (not tilde but something else)

**Comment by desvox** [comment]
> This causes MANY problems.

Nope. You're using a version older than what the client was written for. I agree with you that 3.5 is unreasonable as the only supported version due to update policies on stable systems, and it was never stated explicitly in my documentation. Honestly, I don't recall trying it on 3.4 before you mentioned it to me. But, star expansion is used A LOT to create the lists urwid needs for its widgets. This feauture is part of 3.5. Its not a 'problem' to take advantage of newer features in the language.

> As such, I'm left out of using BBJ for the community I'm a part of. (not tilde but something else)

Im working on changes to get it to run on 3.4. I think list construction is the only thing that i need to change.

**Comment by desvox** [comment]
@MineRobber9000 Done. Let me know if anything else is broken when you set it up there.
